# Generated by Django 5.0.7 on 2024-07-14 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("artist", models.CharField(max_length=200)),
                ("image_url", models.URLField(max_length=300)),
                ("lyrics", models.TextField()),
                ("danceability", models.FloatField(null=True)),
                ("energy", models.FloatField(null=True)),
                ("tempo", models.FloatField(null=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="app.playlist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Song",
        ),
    ]
