# Generated by Django 5.0.7 on 2024-07-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_playlist_track_delete_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="acousticness",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="speechiness",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="valence",
            field=models.FloatField(null=True),
        ),
    ]
