# Generated by Django 5.0.7 on 2024-07-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_track_acousticness_track_speechiness_track_valence"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="popularity",
            field=models.FloatField(null=True),
        ),
    ]
